### ISSUE TITLE
Better RPC handler

### ISSUE THREAD

**Issue by rndquu** [ubiquity/rpc-handler#62]
`rpc-handler` may return RPC node which is:
- out of sync (i.e. [^05^] [^04^] [^02^] [^01^] not on the latest block) 
- not accessible for the end user (like https://eth.llamarpc.com for me which works only via VPN)
- not reliable like `https://eth.drpc.org` (which responds to `eth_getBlock` but hangs for further requests which [causes](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/actions/runs/13383655396/job/37376464060) `text-conversation-rewards` plugin to compute rewards for ~15 minutes instead of 15 seconds)

As a part of this task we should fix all of the above issues. [^03^]

[^01^]: ⚠ 76% possible duplicate - [Implement Dynamic RPC pick handler](https://www.github.com/ubiquity/rpc-handler/issues/3#3)

[^02^]: ⚠ 77% possible duplicate - [Improve trust ratio of rpcs served](https://www.github.com/ubiquity/rpc-handler/issues/60#60)

[^03^]: ⚠ 77% possible duplicate - [Extend RPC-Handler class using Ethers ](https://www.github.com/ubiquity/rpc-handler/issues/61#61)

[^04^]: ⚠ 78% possible duplicate - [Proxify returned provider](https://www.github.com/ubiquity/rpc-handler/issues/23#23)

[^05^]: ⚠ 78% possible duplicate - [Proxy issues](https://www.github.com/ubiquity/rpc-handler/issues/56#56)

**Comment by rndquu** [comment]
@Keyrxng Pls check the description and confirm if it's relevant

**Comment by Keyrxng** [comment]
> (@zugdev did it great [here](https://github.com/ubiquity/permit2-allowance.ubq.fi/blob/04587e0f5324e794e587b9ee59a8246984c4d00f/static/constants.ts))

The only providers/explorers missing from the RPC handler which are included in the link are these listed below so it's redundant in my opinion.

- https://rpc.worldchain.network
- https://explorer.worldchain.network
- https://blast.drpc.org

Both `worldchain` urls are broken links that lead to `This domain is registered at Dynadot.com.` but the `RPC-handler` does support `oneworldchain` and has multiple entries for provider and explorers. Idk if the links are broken just for me or everyone, might be my ISP.

I just fresh installed the `RPC-handler` package and used `ctrl + f` to detect which rpcs and explorers are in the current build via `index.js` using that list you linked.

---

If we were to add our own endpoints that we host or something then it might make sense but public endpoints are pretty much covered and I'd say this task can be closed. 

I'm unaware of the package bugging out and not finding a provider but if a task was opened regarding it I'd be happy to investigate.

> In case rpc-handler fails to find a suitable RPC provider

This should be impossible for the top chains that most use but once we start to deal with less popular chains then it's possible it could but we'd never be able to host whitelisted rpcs for all chains anyway.

**Comment by 0x4007** [comment]
This doesn't make sense because the main functionality of the rpc manager is to fall back until it finds a suitable provider. I agree this should be closed as unplanned.

**Comment by EresDev** [comment]
I have to always use [fallback](https://github.com/ubiquity/pay.ubq.fi/blob/d0a31486cfc3ebe0bf122dc511a9c5a71cedb6fb/shared/use-rpc-handler.ts#L48) around rpc-handler. It is unreliable or the rpcs it provides. 

I have run some tests to show you that rpc-handler needs improvement.
I am running tests using `pay.ubq.fi` test funding using anvil.  What it does? it forks gnosis chains, and does some UUSD transfers. 
Test compares the same operations using rpc provided by rpc-handler, vs simple official `https://rpc.gnosischain.com`

I will put results first, then you can see the video below  me running tests:

- Using official rpc, tests passed: 3/3 times. 100% success rate
- Using rpc-handler's rpc: tests passed: 1/4 times. 25% success rate

Now, there could be problem with some rpc, maybe my ISP blocking some rpc. But it has been very difficult for me to use rpc-handler. 

https://github.com/user-attachments/assets/567c6ac3-27bd-4c78-96d4-10439f954df2

**Comment by Keyrxng** [comment]
I can't say I experienced this personally while building/stabilising the test suites while I was `pay.ubq.fi`'s maintainer. I'm assuming this edge-case only exists in the test suite and it hasn't been a problem in a prod setting?

First of all, `pay.ubq.fi` test env extracts an RPC and then tries to init `Anvil.fork(rpc)` so it does not benefit from retry-reselect which anybody using `rpc-handler` in production would benefit from.

`Anvil.Fork` is a vm essentially and is prone to weird errors within it's infra - see https://www.github.com/foundry-rs/foundry/issues/4082 as one example.

It seems that OS can play into things and I'm a Windows dweeb, which may be why I never experienced it?


Although based on the video (which btw ty) I can make educated guesses.


1. The logic for `rpc-handler` largely remains untouched so I'm inclined to believe at first that it's an Anvil or RPC-specific issue.
2. Based on the error given `Fork Error.. "invalid number"` - I'd begin debugging there, starting with using the RPCs which bugged out and running them n times to see how often they fail. I'd then see if changing the numbers either in terms of value or how they are fed as input (E.G. hex/dec) makes a difference. It's a pretty shit error message but maybe it's talking about a number unrelated to the payload we provide and it's something anvil is inserting for gas for example.
3. Potentially a `cache` issue that's causing it, again on the Anvil side.
4. The fact it succeeds against RPC-A and fails against RPC-B with the same payload, could be that the RPC API is different in some way (which does happen, most commonly with methods tho not input schema).

The fact that `rpc-handler` successful performed it's health-check against those RPC and it was deemed the fastest to respond followed by Anvil's failure to execute a forked tx, I'd lean on it being Anvil more so than `rpc-handler`. Ofc I'm basically stabbing in the dark without looking into things properly.

If needed, open a task and tag me and I'll look into things, happy to help.

**Comment by Keyrxng** [comment]
> In case rpc-handler fails to find a suitable RPC provider it makes sense to fallback to a whitelisted RPC provider.

Which of the below options is the spec implying?

A) `rpc-handler` was not able to find a _singular_ provider for a specific network as-in no suitable providers were found post-health check?
B) A read/write op failed with the given provider(s) and we'd like to fallback to "official" ones in the case where the op failed?

> (@zugdev did it great [here](https://github.com/ubiquity/permit2-allowance.ubq.fi/blob/04587e0f5324e794e587b9ee59a8246984c4d00f/static/constants.ts))

The code reads like A, `rpc-handler` could not find even one provider for that network.

In either case, I think your example @EresDev (without knowledge of it happening through intended usage of `rpc-handler`) doesn't quite apply due to the fact we extract the `RPC` and then the error happens within `Anvil`. I could be wrong tho it would need debugged specifically for me to know for sure.

**Comment by 0x4007** [comment]
Funded because 25% is not a good success rate https://github.com/ubiquity/rpc-handler/issues/62#issuecomment-2661285278

Obviously its preferred we fix the rpc-manager but that will be much more complex than implementing this task.

**Comment by Keyrxng** [comment]
> Funded because 25% is not a good success rate [#62 (comment)](https://github.com/ubiquity/rpc-handler/issues/62#issuecomment-2661285278)
> 
> Obviously its preferred we fix the rpc-manager but that will be much more complex than implementing this task.

Again, the problem by my estimation lies with Anvil, not `rpc-handler`. 

Any "official" RPCs that you guys add, are already inside `rpc-handler`.  The problem presented by @EresDev is detached from the `rpc-handler`'s main logic because we extract the RPC URL to init anvil with it, so no retry or reselect.

**Comment by EresDev** [comment]
> Again, the problem by my estimation lies with Anvil, not rpc-handler.

maybe we should run the same tests without anvil? do the similar transfers for very small amounts and see what is the result. Gnosis chain is very inexpensive to run such tests.  I will run some more tests without anvil and share the results here.

**Comment by rndquu** [comment]
Overall there're at least 2 repos ([one](https://github.com/ubiquity/permit2-allowance.ubq.fi/blob/04587e0f5324e794e587b9ee59a8246984c4d00f/static/constants.ts), [two](https://github.com/ubiquity/pay.ubq.fi/blob/d0a31486cfc3ebe0bf122dc511a9c5a71cedb6fb/shared/use-rpc-handler.ts#L48)) that use their own RPCs in case `rpc-handler` fails which is not a good sign.

As far as I understand `rpc-handler` works this way:
1. Fetch RPCs from https://chainid.network/chains.json for a given network
2. Send `eth_getBlockByNumber` for each RPC and measure latency
3. Return RPC with the lowest latency

The thing is that any latency <500ms looks good for an end user so this parameter is important but not the most crucial one. What's more important is the correct latest block number which means that RPC node is in sync with the latest state. Check this screenshot which highlights RPC with low latency but wrong latest block number:
<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/559abfac-09cb-42f5-89f3-07a75b4b0cf2" />

So the fastest RPC may not be reliable in the end (for example I regularly have issues with https://eth.drpc.org RPC).

We've already discarded the following options:
1. Use self-hosted RPC node (had issues with cloudflare setup)
2. Use private RPC nodes from alchemy or similar services (have to expose API keys in the frontend)

We could mark certain RPC nodes as "stable". I mean that I personally sure that `https://eth.llamarpc.com` is a pretty stable choice for mainnet while `https://rpc.gnosischain.com` is stable for gnosis chain although their latencies may not be the fastest. 

We could change the sorting algorithm of `rpc-handler` to:
1. Send `eth_getBlockByNumber` for each "stable" RPC and measure latency
2. If there is at least 1 live "stable" RPC then return it
3. Fetch RPCs from https://chainid.network/chains.json for a given network (excluding "stable" RPCs from that list)
4. Send `eth_getBlockByNumber` for each "unstable" RPC and measure latency
5. Simply return RPC with the lowest latency

**Comment by Keyrxng** [comment]
The reason `rpc-handler` was built was to avoid building a `blacklist` of RPCs that didn't work (for `pay.ubq.fi`), so to me we should avoid manually marking providers if we can.

It's still unclear what the problem question is:

1. `rpc-handler` could not find any providers? The footage shows providers returned successfully.
2. `rpc-handler` fails to handle tx failures? The footage does not have retry-reselect logic and was relying on Anvil internals to fake broadcast txs.

Difficult for us to determine sync but maybe we can use the majority value of `blocknumbers` and eliminate outliers that way?

> I mean that I personally sure that https://eth.llamarpc.com is a pretty stable choice for mainnet while https://rpc.gnosischain.com is stable for gnosis chain although their latencies may not be the fastest.

You made a comment which sort of attests to the fact even our whitelisted rpcs might fail for some, it feels like a losing battle.

> Rndquu: Somehow [llamarpc](https://github.com/ubiquity/permit2-allowance.ubq.fi/blob/ed60b768508672cb336caf48210fd90f0a22843f/static/main.ts#L26) provider works only with VPN enabled :(

---

Also it appears that the "fallback" logic was leftover and not removed once they got a hang of using `rpc-handler` within `allowance.ubq.fi` so I'm assuming that can be removed (I briefly scanned the commits).


> ZugDev: I take back what I said about using Alchemy. @ubiquity-dao/rpc-handler is super sick, works great, will use it everywhere.
> ZugDev: now using rpc-handler here and in permit2-allowance.ubq.fi,

---

> > Again, the problem by my estimation lies with Anvil, not rpc-handler.

> maybe we should run the same tests without anvil? do the similar transfers for very small amounts and see what is the result. Gnosis chain is very inexpensive to run such tests. I will run some more tests without anvil and share the results here.

Great idea yeah. I'm confident that in a production setting without Anvil, your retry-reselect logic will kick in and your tx will go through.

It's still unconfirmed if anyone has spotted issues in a prod setting, so my opinion is based on the fact there has been none.

**Comment by rndquu** [comment]
> It's still unclear what the problem question is:

`rpc-handler` may return RPC node which is:
- out of sync (i.e. not on the latest block) 
- not accessible for the end user (like https://eth.llamarpc.com for me which works only via VPN)
- not reliable like `https://eth.drpc.org` (which responds to `eth_getBlock` but hangs for further requests which [causes](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/actions/runs/13383655396/job/37376464060) `text-conversation-rewards` plugin to compute rewards for ~15 minutes instead of 15 seconds)

**Comment by Keyrxng** [comment]
1. Sync we can semi-estimate comparing `blocknumbers` I'd think, ofc it relies on a given network having a surplus of providers and the majority being in sync.
2. I'd expect the initial health-check to fail in such a case but either way the expectation of `rpc-handler` would be to activate it's internal retry-reselect logic I'd think. Perhaps it should be looked at if it's failing in those cases.
3. That's tricky. I guess we could `best out of three` for each provider? Pros and cons with this idk if it's optimal for the likes of ETH with 15+ providers etc.

We could call `_getBlock` to eliminate outliers then use an "expensive" read with an immutable return value to further knockout any that might hang, something like `permit2` or whatever comes to mind.

**Comment by 0x4007** [comment]
> not reliable like https://eth.drpc.org (which responds to eth_getBlock but hangs for further requests which causes text-conversation-rewards plugin to compute rewards for ~15 minutes instead of 15 seconds)

I did an implementation that compared permit2 bytecode. That seemed very reliable.

**Comment by Keyrxng** [comment]
Where did we land on things then since this is priced and ready to go?

**Comment by rndquu** [comment]
> Where did we land on things then since this is priced and ready to go?

I've removed fallback to a whitelisted RPC from the issue description. Now it simply describes 3 `rpc-handler` issues that should be solved.

**Comment by Keyrxng** [comment]
I just realized it's `Priority: 3 (High)` so I'm excluded from this task actually lmao. 

The task access is pretty grim rn, especially with marketing contacting hundreds of devs as we speak. Any that are decent will be restricted to menial tasks which won't excite them to partake. 

I know it was a temp fix to stop the team from being overloaded by sub-par PRs from new contributors but maybe things need reviewed a bit.

**Comment by Keyrxng** [comment]
https://github.com/ubiquity/rpc-handler/pull/63 - open and ready for review (still can't request reviews 😂)

> not accessible for the end user (like https://eth.llamarpc.com/ for me which works only via VPN)

I have a feeling that was exposed after the hardcoded RPCs [here](https://github.com/ubiquity/permit2-allowance.ubq.fi/blob/04587e0f5324e794e587b9ee59a8246984c4d00f/static/constants.ts#L4) and not from `rpc-handler` usage. If you called this from a FE the reqs would fail and it wouldn't be considered an option or if it was, the failed tx would be retried with other providers.

Debugging that is difficult for me. If you run `yarn build; npx tsx tests/script-test.ts` it'll show which RPCs are included as options, could you maybe try that? For me it's usable:

![Image](https://github.com/user-attachments/assets/ae84aa36-9a7d-4106-88b7-8c4bcf81633e)
